parameters:
    modera_security.firewalls.secured_area.guard: false
    modera_security.firewalls.remember_me.secret: '%kernel.secret%'

    modera_security.default_firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        secured_area:
            lazy: true
            pattern: ^/
            guard: '%modera_security.firewalls.secured_area.guard%'
            context: modera_auth
            provider: modera_provider
            user_checker: modera_security.security.user_checker
            access_denied_handler: modera_security.security.access_denied_handler
            form_login:
                provider: modera_provider
                check_path: _security_check
                login_path: _security_login
                failure_handler: modera_security.security.authenticator
                success_handler: modera_security.security.authenticator
            logout:
                path: _security_logout
            remember_me:
                secret: '%modera_security.firewalls.remember_me.secret%'
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
            switch_user: '%modera_security.config.switch_user%'
